import type { Agent, CategoryMeta } from "./types";

export const CATEGORIES: CategoryMeta[] = [
  {
    id: "rebalancing",
    label: "Rebalancing",
    clause: "Form A — LP Range Management",
    verb: "manages LP ranges, resets positions automatically",
    blurb:
      "LP ranges drift with price. Every agent here resets its range and writes the realized cost delta on-chain — not an APR screenshot.",
  },
  {
    id: "grid-trading",
    label: "Grid Trading",
    clause: "Form B — Grid Order Management",
    verb: "places and manages automated grid orders",
    blurb:
      "Grid orders live or die on realized spread, not backtest. Every fill this cycle is in the manifest below the band.",
  },
  {
    id: "yield",
    label: "Yield Optimisation",
    clause: "Form C — Liquidity Routing",
    verb: "routes liquidity to the highest available APR",
    blurb:
      "A yield agent is judged on what it beats, not what it chased. Every APY shown here is checked against the manifest at settlement.",
  },
  {
    id: "health-factor",
    label: "Health Factor Monitoring",
    clause: "Form D — Liquidation Defense",
    verb: "protects lending positions from liquidation",
    blurb:
      "A health-factor agent only matters in the minutes before liquidation. Every band below is measured against real drawdowns, not calm markets.",
  },
];

export const AGENTS: Agent[] = [
  // ---------------- Rebalancing ----------------
  {
    id: "meridian-rebalancer",
    name: "Meridian Rebalancer",
    category: "rebalancing",
    tagline: "Resets your PancakeSwap v3 range before it drifts out of bounds.",
    description:
      "Meridian watches BNB/USDT and BNB/FDUSD concentrated positions on PancakeSwap v3 and re-centers them before price exits the fee-earning range, netting out gas and slippage against a static-range baseline.",
    operator: "Fielding Labs",
    agentId8004: "bnb:56 · agent #10281",
    network: "BSC Mainnet",
    protocols: ["PancakeSwap v3"],
    feeModel: "0.4% of fees captured, 6% of that to the assurance pool",
    poolContribution: "6% of performance fee",
    cyclesCompleted: 182,
    hirers: 64,
    manifestHash: "0x7a41c0e2f4a6c8e0f2a4b6d8f0a2c4e6f8a0b2c4d6e8f0a2c4e6f8a0b2c4d6e8",
    jobStage: "SETTLED",
    band: {
      symbol: "",
      unit: "bps saved vs. static range",
      scaleMin: 20,
      scaleMax: 140,
      historicalLow: 40,
      historicalHigh: 95,
      promisedLow: 55,
      promisedHigh: 85,
      realized: 71,
      cycleLabel: "Cycle 183",
      status: "within",
    },
  },
  {
    id: "tideline-ranger",
    name: "Tideline Ranger",
    category: "rebalancing",
    tagline: "Parks idle liquidity in Venus between PancakeSwap range resets.",
    description:
      "Tideline holds two legs: an active PancakeSwap v3 range and a Venus deposit for capital waiting on the sideline. It reduces the drag of sitting fully out-of-range, then re-enters when price returns to a profitable band.",
    operator: "Fielding Labs",
    agentId8004: "bnb:56 · agent #10282",
    network: "BSC Mainnet",
    protocols: ["PancakeSwap v3", "Venus"],
    feeModel: "0.5% of fees captured, 6% of that to the assurance pool",
    poolContribution: "6% of performance fee",
    cyclesCompleted: 96,
    hirers: 21,
    manifestHash: "0x1c3e5a7c9e0f2a4c6e8a0c2e4a6c8e0a2c4e6a8c0e2a4c6e8a0c2e4a6c8e0a2c",
    jobStage: "SETTLED",
    band: {
      symbol: "",
      unit: "bps saved vs. static range",
      scaleMin: 10,
      scaleMax: 100,
      historicalLow: 32,
      historicalHigh: 78,
      promisedLow: 45,
      promisedHigh: 70,
      realized: 38,
      cycleLabel: "Cycle 97",
      status: "breach",
      rebate: {
        amount: "0.9% of position value",
        clause: "Clause 97(a)",
        note: "Realized 38 bps against a 45 bps floor — the Venus leg under-yielded during a low-volatility week, so the out-of-range parking gained less than promised.",
      },
    },
  },
  {
    id: "arclight-rebalance",
    name: "Arclight Rebalance",
    category: "rebalancing",
    tagline: "Runs tighter PancakeSwap ranges on BNB/ETH for higher fee capture.",
    description:
      "Arclight trades range width for fee density — narrower bands on the BNB/ETH v3 pool, rebalanced roughly every 40 minutes during active hours. Built for hirers who want more of their capital earning at any given moment.",
    operator: "Dromon Systems",
    agentId8004: "bnb:56 · agent #10412",
    network: "BSC Mainnet",
    protocols: ["PancakeSwap v3"],
    feeModel: "0.6% of fees captured, 6% of that to the assurance pool",
    poolContribution: "6% of performance fee",
    cyclesCompleted: 340,
    hirers: 89,
    manifestHash: "0x9d1f3b5d7f9b1d3f5b7d9f1b3d5f7b9d1f3b5d7f9b1d3f5b7d9f1b3d5f7b9d1f",
    jobStage: "SETTLED",
    band: {
      symbol: "",
      unit: "bps saved vs. static range",
      scaleMin: 20,
      scaleMax: 150,
      historicalLow: 50,
      historicalHigh: 125,
      promisedLow: 60,
      promisedHigh: 110,
      realized: 98,
      cycleLabel: "Cycle 341",
      status: "within",
    },
  },

  // ---------------- Grid Trading ----------------
  {
    id: "tideline-grid",
    name: "Tideline Grid",
    category: "grid-trading",
    tagline: "Runs a 24-line grid on BNB/USDT, sized to realised volatility.",
    description:
      "Tideline Grid places and re-places limit orders across a band centred on recent realised volatility, harvesting the spread on BNB/USDT without taking a directional position.",
    operator: "Cordage Collective",
    agentId8004: "bnb:56 · agent #11004",
    network: "BSC Mainnet",
    protocols: ["PancakeSwap v3"],
    feeModel: "1.1% of position value per cycle, 6% of that to the assurance pool",
    poolContribution: "6% of performance fee",
    cyclesCompleted: 118,
    hirers: 47,
    manifestHash: "0x4e2a6f0c1d8b3a7e2f905c1a44e0b7d3f8c1a9e0d2b4f6a8c0e2f4a6c8e0f2a4",
    jobStage: "SUBMITTED",
    band: {
      symbol: "%",
      unit: "cycle return",
      scaleMin: 0,
      scaleMax: 12,
      historicalLow: 4.6,
      historicalHigh: 8.9,
      promisedLow: 6.2,
      promisedHigh: 8.4,
      realized: 4.1,
      cycleLabel: "Cycle 14 of 20",
      status: "breach",
      rebate: {
        amount: "0.42% of position value",
        clause: "Clause 14(a)",
        note: "Realized 4.10% fell 0.5 pt below the promised floor. The pool paid out against the same manifest hash shown at hire — no dispute filed.",
      },
    },
  },
  {
    id: "cordgrid",
    name: "Cordgrid",
    category: "grid-trading",
    tagline: "A tight, high-frequency grid built for BNB/USDT's usual range.",
    description:
      "Cordgrid runs a narrower grid than Tideline, rebalancing lines more often to stay inside typical daily volatility. Lower variance, lower ceiling.",
    operator: "Cordage Collective",
    agentId8004: "bnb:56 · agent #11005",
    network: "BSC Mainnet",
    protocols: ["PancakeSwap v3"],
    feeModel: "0.9% of position value per cycle, 6% of that to the assurance pool",
    poolContribution: "6% of performance fee",
    cyclesCompleted: 210,
    hirers: 58,
    manifestHash: "0x2b4d6f8a0c2e4a6c8e0a2c4e6a8c0e2a4c6e8a0c2e4a6c8e0a2c4e6a8c0e2a4c",
    jobStage: "SETTLED",
    band: {
      symbol: "%",
      unit: "cycle return",
      scaleMin: 0,
      scaleMax: 10,
      historicalLow: 4.0,
      historicalHigh: 8.6,
      promisedLow: 5.5,
      promisedHigh: 7.8,
      realized: 6.9,
      cycleLabel: "Cycle 211",
      status: "within",
    },
  },
  {
    id: "palisade-grid",
    name: "Palisade Grid",
    category: "grid-trading",
    tagline: "A wide, volatility-adaptive grid for BNB/ETH swings.",
    description:
      "Palisade widens or narrows its grid spacing against a rolling volatility window, aimed at BNB/ETH's larger, less frequent moves rather than daily chop.",
    operator: "Dromon Systems",
    agentId8004: "bnb:56 · agent #11098",
    network: "BSC Mainnet",
    protocols: ["PancakeSwap v3"],
    feeModel: "1.3% of position value per cycle, 6% of that to the assurance pool",
    poolContribution: "6% of performance fee",
    cyclesCompleted: 74,
    hirers: 19,
    manifestHash: "0x6c8e0a2c4e6a8c0e2a4c6e8a0c2e4a6c8e0a2c4e6a8c0e2a4c6e8a0c2e4a6c8e",
    jobStage: "SETTLED",
    band: {
      symbol: "%",
      unit: "cycle return",
      scaleMin: 0,
      scaleMax: 16,
      historicalLow: 5.8,
      historicalHigh: 13.0,
      promisedLow: 7.0,
      promisedHigh: 11.5,
      realized: 9.8,
      cycleLabel: "Cycle 75",
      status: "within",
    },
  },

  // ---------------- Yield ----------------
  {
    id: "cistern-yield",
    name: "Cistern Yield",
    category: "yield",
    tagline: "Routes idle stablecoins to the best verified APR across Venus and PancakeSwap.",
    description:
      "Cistern re-checks lending and LP yields every epoch and moves capital to whichever verified venue is paying the most, net of the gas cost of moving — never chasing an unverified or momentary spike.",
    operator: "Reservoir Systems",
    agentId8004: "bnb:56 · agent #12203",
    network: "BSC Mainnet",
    protocols: ["Venus", "PancakeSwap v3"],
    feeModel: "8% of yield earned, 6% of that to the assurance pool",
    poolContribution: "6% of performance fee",
    cyclesCompleted: 44,
    hirers: 133,
    manifestHash: "0x8f0a2c4e6a8c0e2a4c6e8a0c2e4a6c8e0a2c4e6a8c0e2a4c6e8a0c2e4a6c8e0a",
    jobStage: "SUBMITTED",
    band: {
      symbol: "%",
      unit: "APY",
      scaleMin: 0,
      scaleMax: 14,
      historicalLow: 6.9,
      historicalHigh: 9.8,
      promisedLow: 7.8,
      promisedHigh: 9.4,
      realized: 6.6,
      cycleLabel: "Epoch 4",
      status: "breach",
      rebate: {
        amount: "1.10% deposit credit",
        clause: "Clause 4(c)",
        note: "Realized 6.60% APY against a 7.8% floor — a Venus rate drop mid-epoch outpaced the routing agent's rebalance window.",
      },
    },
  },
  {
    id: "reservoir-apr",
    name: "Reservoir APR",
    category: "yield",
    tagline: "Splits deposits across Venus and PancakeSwap LP for a blended rate.",
    description:
      "Reservoir holds a standing split between lending and LP positions rather than moving fully into one venue, trading some upside for a smoother realised rate.",
    operator: "Reservoir Systems",
    agentId8004: "bnb:56 · agent #12204",
    network: "BSC Mainnet",
    protocols: ["Venus", "PancakeSwap v3"],
    feeModel: "7% of yield earned, 6% of that to the assurance pool",
    poolContribution: "6% of performance fee",
    cyclesCompleted: 61,
    hirers: 52,
    manifestHash: "0x0a2c4e6a8c0e2a4c6e8a0c2e4a6c8e0a2c4e6a8c0e2a4c6e8a0c2e4a6c8e0a2c",
    jobStage: "SETTLED",
    band: {
      symbol: "%",
      unit: "APY",
      scaleMin: 0,
      scaleMax: 14,
      historicalLow: 7.6,
      historicalHigh: 11.0,
      promisedLow: 8.5,
      promisedHigh: 10.2,
      realized: 9.4,
      cycleLabel: "Epoch 62",
      status: "within",
    },
  },
  {
    id: "spillway-yield",
    name: "Spillway Yield",
    category: "yield",
    tagline: "Stablecoin-only routing across FDUSD and USDT lending markets.",
    description:
      "Spillway stays entirely in stablecoins, moving between FDUSD and USDT lending markets on Venus. Lowest variance of the yield agents, built for treasuries that can't take principal risk.",
    operator: "Cordage Collective",
    agentId8004: "bnb:56 · agent #12250",
    network: "BSC Mainnet",
    protocols: ["Venus"],
    feeModel: "5% of yield earned, 6% of that to the assurance pool",
    poolContribution: "6% of performance fee",
    cyclesCompleted: 152,
    hirers: 201,
    manifestHash: "0xc4e6a8c0e2a4c6e8a0c2e4a6c8e0a2c4e6a8c0e2a4c6e8a0c2e4a6c8e0a2c4e6",
    jobStage: "SETTLED",
    band: {
      symbol: "%",
      unit: "APY",
      scaleMin: 0,
      scaleMax: 8,
      historicalLow: 4.2,
      historicalHigh: 6.6,
      promisedLow: 4.8,
      promisedHigh: 6.0,
      realized: 5.3,
      cycleLabel: "Epoch 153",
      status: "within",
    },
  },

  // ---------------- Health Factor ----------------
  {
    id: "sentry-hf",
    name: "Sentry HF",
    category: "health-factor",
    tagline: "Watches Venus positions block by block and de-risks before liquidation.",
    description:
      "Sentry monitors health factor on Venus borrow positions continuously and de-levers in stages as HF approaches its floor, aiming to keep hirers inside a promised safety band even through fast drawdowns.",
    operator: "Bastion Watch",
    agentId8004: "bnb:56 · agent #13051",
    network: "BSC Mainnet",
    protocols: ["Venus"],
    feeModel: "0.15% of position value per month, 6% of that to the assurance pool",
    poolContribution: "6% of performance fee",
    cyclesCompleted: 2400,
    hirers: 76,
    manifestHash: "0xe0a2c4e6a8c0e2a4c6e8a0c2e4a6c8e0a2c4e6a8c0e2a4c6e8a0c2e4a6c8e0a2",
    jobStage: "SUBMITTED",
    band: {
      symbol: "",
      unit: "HF maintained",
      scaleMin: 1.0,
      scaleMax: 1.9,
      historicalLow: 1.28,
      historicalHigh: 1.62,
      promisedLow: 1.35,
      promisedHigh: 1.55,
      realized: 1.22,
      cycleLabel: "Window 006",
      status: "breach",
      rebate: {
        amount: "0.31 BNB",
        clause: "Clause 6(b)",
        note: "HF dropped to 1.22 against a 1.35 floor during a fast margin move — the de-lever stage triggered late. Pool paid out before the position was four blocks old.",
      },
    },
  },
  {
    id: "parapet-watch",
    name: "Parapet Watch",
    category: "health-factor",
    tagline: "Conservative HF defense for larger Venus positions.",
    description:
      "Parapet holds wider safety margins by default and de-levers earlier, aimed at hirers running larger positions who'd rather give up some capital efficiency than get close to the edge.",
    operator: "Bastion Watch",
    agentId8004: "bnb:56 · agent #13052",
    network: "BSC Mainnet",
    protocols: ["Venus"],
    feeModel: "0.12% of position value per month, 6% of that to the assurance pool",
    poolContribution: "6% of performance fee",
    cyclesCompleted: 1180,
    hirers: 44,
    manifestHash: "0xa4c6e8a0c2e4a6c8e0a2c4e6a8c0e2a4c6e8a0c2e4a6c8e0a2c4e6a8c0e2a4c6",
    jobStage: "SETTLED",
    band: {
      symbol: "",
      unit: "HF maintained",
      scaleMin: 1.0,
      scaleMax: 2.1,
      historicalLow: 1.40,
      historicalHigh: 1.95,
      promisedLow: 1.50,
      promisedHigh: 1.80,
      realized: 1.68,
      cycleLabel: "Window 1181",
      status: "within",
    },
  },
  {
    id: "bastion-guard",
    name: "Bastion Guard",
    category: "health-factor",
    tagline: "HF defense tuned for leveraged Aave v3 positions on BSC.",
    description:
      "Bastion is built for hirers running closer to the edge on purpose — tighter monitoring cadence, smaller de-lever steps, aimed at Aave v3 borrowers who want to stay leveraged as long as it's safe to.",
    operator: "Dromon Systems",
    agentId8004: "bnb:56 · agent #13210",
    network: "BSC Mainnet",
    protocols: ["Aave V3"],
    feeModel: "0.18% of position value per month, 6% of that to the assurance pool",
    poolContribution: "6% of performance fee",
    cyclesCompleted: 3050,
    hirers: 112,
    manifestHash: "0x6a8c0e2a4c6e8a0c2e4a6c8e0a2c4e6a8c0e2a4c6e8a0c2e4a6c8e0a2c4e6a8c",
    jobStage: "SETTLED",
    band: {
      symbol: "",
      unit: "HF maintained",
      scaleMin: 1.0,
      scaleMax: 1.7,
      historicalLow: 1.10,
      historicalHigh: 1.48,
      promisedLow: 1.20,
      promisedHigh: 1.40,
      realized: 1.31,
      cycleLabel: "Window 3051",
      status: "within",
    },
  },
];

export function getAgent(id: string): Agent | undefined {
  return AGENTS.find((a) => a.id === id);
}

export function agentsByCategory(category: string): Agent[] {
  return AGENTS.filter((a) => a.category === category);
}

export function categoryMeta(category: string): CategoryMeta | undefined {
  return CATEGORIES.find((c) => c.id === category);
}
